### ISSUE TITLE
Feature request ios-deploy to list device id in a clean way

### ISSUE THREAD

**Issue by csantanapr** [phonegap/ios-deploy#154] opened 2015-06-26 02:25 UTC
It will be nice to run ios-deploy to get a list of target ids that later can be use in 
cordova run --target=realdeviceid or 
ios-deploy -i or 
ionic run --target

ios-sim already supports this for simulators with "ios-sim showdevicetypes"

Maybe something like "ios-deploy showconnecteddevices"
and it only shows the device ids

Is ios-deploy -c what is suppose to do, it prints too much info for user, it will be a nice clean output just with the id or more clear which portion is the id, something that another tool can call ios-deploy and the output is easy to parse

**Comment by shazron** [comment] 2015-06-26 16:36
Thanks Carlos - this is essentially what #125 is asking for

**Comment by shazron** [comment] 2015-07-11 00:35
Closing as dupe of #125

**Closed by shazron** 2015-07-11 00:35 UTC
