### ISSUE TITLE
unable to locate DeviceSupport directory

### ISSUE THREAD

**Issue by Robertbaelde** [phonegap/ios-deploy#292] opened 2017-06-08 12:15 UTC
When i run the command ionic cordova run ios --device, it fails with the following error message: 

`2017-06-08 14:09:23.954 ios-deploy[8886:63961] [ !! ] Unable to locate DeviceSupport directory. This probably means you don't have Xcode installed, you will need to launch the app manually and logging output will not be shown!
Error: Error code 253 for command: ios-deploy with args: --justlaunch,--no-wifi,-d,-b,/Users/robert/code/bitscanapp/platforms/ios/build/device/bitscanapp.app`

The full command ionic/cordova tries to execute: 'ios-deploy with args: --justlaunch,--no-wifi,-d,-b,/Users/robert/code/bitscanapp/platforms/ios/build/device/bitscanapp.app'

What could be the issue? I reinstalled cordova, ionic, npm and xcode.. 

# System Specs

Please run the commands below in your Terminal.app and include it in the issue. Check when done and include results below.

- [x] 1. system_profiler SPSoftwareDataType
system_profiler SPSoftwareDataType
Software:

    System Software Overview:

      System Version: macOS 10.12.4 (16E195)
      Kernel Version: Darwin 16.5.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Computer Name: MacBook Pro van Robert
      User Name: Robert Baelde (robert)
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 44 minutes

- [x] 2. ios-deploy -V
1.9.1
- [x] 3. xcodebuild -version
Xcode 8.3.3
Build version 8E3004b
- [x] 4. xcode-select --print-path
/Applications/Xcode.app/Contents/Developer
- [x] 5. gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.1.0 (clang-802.0.42)
Target: x86_64-apple-darwin16.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
- [x] 6. lldb --version
lldb-370.0.42
  Swift-3.1

**Comment by larssn** [comment] 2017-06-08 13:00
There was an update yesterday I think, Xcode 8.3.3. I have the same problem.

**Comment by trumbitta** [comment] 2017-06-08 14:17
@Robertbaelde could you fix the typo in the issue title? It's making searches for that same error message fail :)

**Comment by thegreatsunra** [comment] 2017-06-08 19:36
Same issue here with a very similar system configuration as @Robertbaelde.

I am able to build my Cordova app manually to a targeted device from within Xcode, but `cordova run ios --device` throws a `Unable to locate DeviceSupport directory` error.

```bash
$ system_profiler SPSoftwareDataType

Software:

    System Software Overview:

      System Version: macOS 10.12.5 (16F73)
      Kernel Version: Darwin 16.6.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Computer Name: Swiftcurrent
      User Name: Dane Petersen (dane)
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 2 days 4:48
```

```bash
$ ios-deploy -V      
               
1.9.1
```

```bash
$ xcodebuild -version

Xcode 8.3.3
Build version 8E3004b
```

```bash
$ xcode-select --print-path

/Applications/Xcode.app/Contents/Developer
```

```bash
$ gcc --version

Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.1.0 (clang-802.0.42)
Target: x86_64-apple-darwin16.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

```bash
$ lldb --version

lldb-370.0.42
  Swift-3.1
```

**Comment by larssn** [comment] 2017-06-08 19:56
The change notes for Xcode 8.3.3 says:

## Installing Device Support
Run from the command-line, Xcode.app takes the new command-line argument, `-installComponents`. When Xcode is run from a command-line script with this option, it installs the required device support packages and then quits. (15127411)

However, I haven't been able to make it work.
Doing `open -a Xcode --args -installComponents` and following the on-screen instructions is all fine and dandy, but it doesn't help, in my case.

Maybe I'm doing it wrong.

**Comment by thegreatsunra** [comment] 2017-06-08 20:14
@larssn Good snooping. `open -a Xcode --args -installComponents` didn't work for me either.

Xcode opened a dialog box prompting me to "Enable Accessibility access for UI Testing", but no matter what I did, `cordova run ios --device` continued to throw the same `Unable to locate DeviceSupport directory` error.

**Comment by magnushakansson** [comment] 2017-06-09 08:56
I managed to get it to work by creating a symbolic link in /Applications/Xcode.app/Contents/Developer/platforms/iPhoneOS.platform/DeviceSupport

`sudo ln -s 10.3.1\ \(14E8301\)/ 10.3`

**Comment by trumbitta** [comment] 2017-06-09 10:19
@magnushakansson your fix is not working for me. Can you share more about how you chose the `10.3` value?

**Comment by magnushakansson** [comment] 2017-06-09 10:51
I had a machine without the update to 8.3.3 (previous version 8.3.2) and there I have a 10.3 folder. I'm a bit surprised it worked but I have done it on two separate machines and both work well.
You must of course make sure you have the "10.3.1 (14E8301)" folder otherwise you need to change command accordingly.

**Comment by trumbitta** [comment] 2017-06-09 11:30
I have that folder, but using `10.3` as the name of the link didn't make any difference :-/

**Comment by trumbitta** [comment] 2017-06-09 11:58
Using `10.3.2`, the exact version of my target device, did the trick.

So for me it was:

`sudo ln -s 10.3.1\ \(14E8301\)/ 10.3.2`

**Comment by tiagosarmento** [comment] 2017-06-09 12:28
Through a series of events I made ios-deploy to work again, though I am not sure due to which.
This were the actions taken on my side:

1 - I tried the softlink workaround, as proposed by magnushakansson and trumbitta, but without success in my case:
$ sudo ln -s 10.3.2\ \(14F89)/ 10.3\ \(14E269)

2 - Update of iTunes
My iOS Devices weren't being seen by iTunes this morning. I tried several device reboots, unplug->plug USB cable in different ports, all without success. Then I decided to update iTunes, which had no effect in iOS devices discovery.

3 - Update iOS Sierra to 10.12.5
Did an update of iOS Sierra to the latest version, this required a hard-reboot. Since then ios-deploy is back to normal.

Some system and tech details:

- iTunes version is 12.6.1.25
- iOS Sierra version 10.12.5
- iPhone7 iOS 10.3.2 (14F89)
- XCode 8.3.2 (8E2002)

$ ll /Applications/Xcode.app/Contents/Developer/platforms/iPhoneOS.platform/DeviceSupport
drwxrwxr-x  4 root wheel 136 Feb  2 17:23  10.2
drwxrwxr-x  4 root wheel 136 Apr 24 12:39  9.2
drwxrwxr-x  4 root wheel 136 Apr 24 12:39  9.1
drwxrwxr-x  4 root wheel 136 Apr 24 12:39  9.0
drwxrwxr-x  4 root wheel 136 Apr 24 12:39  8.4
drwxrwxr-x  4 root wheel 136 Apr 24 12:39  8.3
drwxrwxr-x  4 root wheel 136 Apr 24 12:39  8.2
drwxrwxr-x  4 root wheel 136 Apr 24 12:39  8.1
drwxrwxr-x  4 root wheel 136 Apr 24 12:39  8.0
drwxrwxr-x  4 root wheel 136 Apr 24 12:39  10.1
drwxrwxr-x  4 root wheel 136 Apr 24 12:39  10.0
drwxrwxr-x  4 root wheel 136 Apr 24 12:39  9.3
drwxrwxr-x  4 root wheel 136 Jun  9 11:10 '10.3 (14E269)'

$ ios-deploy -V 
2.0.0

$ xcodebuild -version
Xcode 8.3.2
Build version 8E2002

$ xcode-select --print-path
/Applications/Xcode.app/Contents/Developer

$ gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/c++/4.2.1
Apple LLVM version 8.1.0 (clang-802.0.42)
Target: x86_64-apple-darwin16.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

$ lldb --version
lldb-370.0.42
Swift-3.1

**Comment by trumbitta** [comment] 2017-06-09 12:33
@tiagosarmento the last available release of `ios-deploy` is `1.9.1`. Did you install it from sources?

**Comment by tiagosarmento** [comment] 2017-06-09 12:48
@trumbitta Yes, I forgot about that point, we build it from sources.

**Comment by rodrigosiqueiradev** [comment] 2017-06-09 20:26
Hey guys, going into /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform
I've found that the folder name for my iOS version (10.3.1) was with a different name, renaming the folder name to (10.3) only made ios-deploy to work again. Not sure why this folder name was different though... Also, for some reason, Xcode doesn't show ios 10.3 available for download.

**Comment by shazron** [comment] 2017-06-10 07:48
I'll take a look.

If you use the `--verbose` flag:
```
tarting debug of iPhone 6s 'Shazron's iPhone 6s' (xxxxxxxxx) connected through USB...
Device Class: iPhone
build: 14F89
version: 10.3.2
version: 10.3
version: 10
2017-06-10 00:43:37.233 ios-deploy[15583:39236601] [ !! ] Unable to locate DeviceSupport directory. This probably means you don't have Xcode installed, you will need to launch the app manually and logging output will not be shown!
```

You can see various version mismatches everywhere. The logging is not quite helpful but gives a clue on what's happening. 

My DeviceSupport listing:
```
/Applications/Xcode.app/Contents/Developer/platforms/iPhoneOS.platform/DeviceSupport  ls
10.0             10.2             8.0              8.2              8.4              9.1              9.3
10.1             10.3.1 (14E8301) 8.1              8.3              9.0              9.2
```

... does not match any of the version 10.3.2 it is trying to find. I am on Xcode 8.3.3 and iOS 10.3.2. Usually with a new iOS update it will have to download the new DeviceSupport symbols from the device...

**Comment by shazron** [comment] 2017-06-10 08:10
The versions: 10.3.2, 10.3, and 10 are the DeviceSupport folders it is trying to find, in my case -- use the `--verbose` flag to see what it is trying to find for yours.

In `/Applications/Xcode.app/Contents/Developer/platforms/iPhoneOS.platform/DeviceSupport` folder, I did:
```
ln -s 10.3.1\ \(14E8301\) 10.3.2
```

... to create a symlink of `10.3.2` to the latest DeviceSupport version available in 10.x.

**Comment by shazron** [comment] 2017-06-10 08:17
In this older version of `ios-deploy` there was a symlink target in the Makefile that created a `Latest` symlink:
https://github.com/phonegap/ios-deploy/blob/1.0.2/Makefile#L19-L20

... which will also work.

**Comment by shazron** [comment] 2017-06-10 08:25
The corrected script should be:
`ln -sfn "`find . -type d -maxdepth 1 -exec basename {} \; | sort -n | tail -1`" Latest`

**Comment by Mumumurilo** [comment] 2017-06-12 12:20
Had the same issue as @rodrigosiqueiradev , his solution worked for me. Thanks!

**Comment by ronligt** [comment] 2017-06-13 07:54
For me the following link worked:

```
cd /Applications/Xcode.app/Contents/Developer/platforms/iPhoneOS.platform/DeviceSupport
ln -s 10.3.1\ \(14E8301\)/ 10.3.2\ \(14F89\)
```
(added the 14F89 version number for 10.3.2)

**Comment by alexM8** [comment] 2017-06-13 09:25
`ln -s 10.3.1\ \(14E8301\)/ 10.3.2` worked for me

**Comment by rodrigosiqueiradev** [comment] 2017-06-14 13:21
@ronligt @alexM8 That works too, it seems ios-deploy searches for the best version match when running. For instance, having a 10.3 would be ok for all subversions of it, but having only 10.3.1 would not work if your device is running iOS 10.3.2.

Rounding everything up, I don't believe this issue should be closed as the problem isn`t with ios-deploy itself. Seems more like an Xcode problem, i'm running version 8.3.3 and it doesn't shows an option to download iOS 10.3 images, weirdly enough... 

Perhaps it should be a new feature? Like, trying an older version if the current one isn't available, warning the user that it was missing.

**Comment by andreloty** [comment] 2017-06-20 18:52
@ronligt solution worked for me!
tks...

**Comment by shawnlan** [comment] 2017-06-21 18:56
Could the solution cause issues for future xCode updates?

**Comment by alx-andru** [comment] 2017-06-22 12:23
@alexM8 worked for me as well

**Comment by kentoj** [comment] 2017-07-01 20:16
@alexM8 Worked for me as well. What is the ongoing way to fix this as new versions of iOS are released?

**Comment by asauber** [comment] 2017-07-04 19:13
Symlinking these files is a fine stopgap to get Phonegap apps to build. However, if you're working on a Phonegap plugin and one of the system libraries has a new version in the new version of iOS, then the names of the debugging symbols won't match their location in memory.

What's strange is when you plug in a 10.3.2 iPhone for the first time, Xcode goes through a process of extracting debugging symbols, but the new directory is not created.

If anyone has experience with native iPhone debugging, please let us know when or how the actual DeviceSupport directory is created.

**Comment by shazron** [comment] 2017-07-27 08:24
Not the perfect solution, but I'm providing the generic shell script that can be run (from my comments above) to create a `Latest` symlink to the latest iOS device support folder: 
```
cd `xcode-select --print-path`/Platforms/iPhoneOS.platform/DeviceSupport
ln -sfn "`find . -type d -maxdepth 1 -exec basename {} \; | sort -n | tail -1`" Latest
```

**Comment by verganas** [comment] 2017-07-27 10:32
@shazron Thanks this worked for me with 10.3.1

**Comment by VitorHFLopes** [comment] 2017-07-28 12:51
thanks @rodrigosiqueiradev \m/

**Comment by lincolnberryiii** [comment] 2017-08-03 09:00
@shazron Thanks, that worked splendidly for me with 10.3.2!

**Comment by shazron** [comment] 2017-08-09 00:37
#299 might fix this (slated for v1.9.2)

**Comment by aguvel** [comment] 2017-08-21 18:38
@rodrigosiqueiradev GÊNIO!!! TINHA QUE SER BR

**Comment by bartvanderwal** [comment] 2017-08-21 20:36
Great! The only thing I had to figure out which version my iPhone had. It's somewhere under  `Settings`, `General` and then `About` as the below gifanim explains/shows:

For me I had to use `10.3.3` instead of the `10.3` in @magnushakansson 's original answer:

>I managed to get it to work by creating a symbolic link in `/Applications/Xcode.app/Contents/Developer/platforms/iPhoneOS.platform/DeviceSupport`:
*`ln -s 10.3.1\ \(14E8301\)/ 10.3`*

![settings-animation](https://user-images.githubusercontent.com/3029472/29537020-6059c05a-86c0-11e7-90cf-04610114ff3e.gif)

**Comment by shazron** [comment] 2017-09-05 08:56
Fixed using #299

**Closed by shazron** 2017-09-05 08:56 UTC
Labels: bug

**Comment by aaleksandroff** [comment] 2017-09-08 11:02
@shazron having the same problem here (error 253), but my iOS device is version 10.2 (14C92) - what is the exact command that can help me?

**Comment by aaleksandroff** [comment] 2017-09-08 11:16
Here's my log:
[XCUITest] Error: Could not install app: 'Command 'ios-deploy --id 808b474cd30e7da9f6d68370952c4842fdca1094 --uninstall --bundle '/var/folders/k_/8qvpw93n6ng_j2t6brmw44gr0000gn/T/201788-6356-vbi5n5.78gmbo6r/Payload/Receipt Bank.app'' exited with code 253'
    at IOSDeploy.install$ (../../lib/ios-deploy.js:38:13)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:109:7)
 Error: Could not install app: 'Command 'ios-deploy --id 808b474cd30e7da9f6d68370952c4842fdca1094 --uninstall --bundle '/var/folders/k_/8qvpw93n6ng_j2t6brmw44gr0000gn/T/201788-6356-vbi5n5.78gmbo6r/Payload/Receipt Bank.app'' exited with code 253'
    at IOSDeploy.install$ (../../lib/ios-deploy.js:38:13)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:109:7)

**Comment by shazron** [comment] 2017-09-08 11:28
@aaleksandroff try https://github.com/phonegap/ios-deploy/issues/292#issuecomment-318294268 or v1.9.2 
also your stack trace is not an ios-deploy stack trace

**Comment by aaleksandroff** [comment] 2017-09-08 11:34
@shazron Did that and my version is 1.9.2, but now [XCUITest] Error: App with bundle identifier 'com.***' unknown

**Comment by aaleksandroff** [comment] 2017-09-08 12:09
@shazron I'm on v1.9.2 and I did:
```
cd `xcode-select --print-path`/Platforms/iPhoneOS.platform/DeviceSupport
ln -sfn "`find . -type d -maxdepth 1 -exec basename {} \; | sort -n | tail -1`" Latest
```
but it's still not working and I'm still getting:
```
[XCUITest] Error: Could not install app: 'Command 'ios-deploy --id 808b474cd30e7da9f6d68370952c4842fdca1094 --uninstall --bundle '/var/folders/k_/8qvpw93n6ng_j2t6brmw44gr0000gn/T/201788-7196-15ugtqm.ftuykwewmi/Payload/Receipt Bank.app'' exited with code 253'
    at IOSDeploy.install$ (../../lib/ios-deploy.js:38:13)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:109:7)
 Error: Could not install app: 'Command 'ios-deploy --id 808b474cd30e7da9f6d68370952c4842fdca1094 --uninstall --bundle '/var/folders/k_/8qvpw93n6ng_j2t6brmw44gr0000gn/T/201788-7196-15ugtqm.ftuykwewmi/Payload/Receipt Bank.app'' exited with code 253'
    at IOSDeploy.install$ (../../lib/ios-deploy.js:38:13)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:109:7)
```
What can I do differently?

**Comment by aaleksandroff** [comment] 2017-09-08 12:36
@shazron I've actually updated my appium version and fixed few things with appium-doctor. Now I'm getting the same error but before that I get:
`[ 70%] VerifyingApplication
'. Stderr: '2017-09-08 15:28:51.409 ios-deploy[7923:6197563] [ !! ] Error 0xe8008001: An unknown error has occurred. AMDeviceSecureInstallApplication(0, device, url, options, install_callback, 0)
'.`

**Comment by nilebma** [comment] 2017-09-09 10:52
In order to make things work on a device with iOS 11 beta (hence using XCode 9 Beta), a simple solution was for me to :

- Copy this folder (or any folder related to version 11 of iOS)

`/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/DeviceSupport/11.0 (15A5361a)`

- Here :

`/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/DeviceSupport/`

**Comment by imadarif** [comment] 2017-09-19 06:40
Goto this path
/Applications/Xcode.app/Contents/Developer/platforms/iPhoneOS.platform/DeviceSupport
by renaming 10.3.1 (14Eac) to 10.3 my error resolved!! and now **ionic cordova run ios** command deploy and start app in my mobile 💯  :)

**Comment by flowli** [comment] 2017-09-20 14:10
Now that Xcode 9.0 is available as stable, this is what worked for me:

cd /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/DeviceSupport
sudo ln -s 11.0\ \(15A372\)/ 11.0

**Comment by piggyslasher** [comment] 2017-09-26 01:38
@trumbitta's fix - renaming the folder worked for me. Find the most recent version that exists (mine was 10.2). I then symlinked 10.2 to 10.3.2 - and everything worked.

**Comment by blackdynamo** [comment] 2017-10-30 22:34
I am still having this issue in 1.9.2 with Xcode 9.0.1. My device is running 11.0.3 (15A432).

I have also tried using the solution to add the symlinks but doesn't seem to work for me. Create a symlink for 11.0.3 (15A432) -> 11.0 (15A372)

```
------ Debug phase ------
Starting debug of 38813d6fae7464bb3f099582ea78ce53955e8632 (N66mAP, iPhone 6s Plus, iphoneos, arm64) a.k.a. 'iPhone' connected through USB...
[  0%] Looking up developer disk image
[ 95%] Developer disk image mounted successfully
2017-10-30 16:25:46.621 ios-deploy[44705:5930783] [ !! ] Unable to locate DeviceSupport directory with suffix 'Symbols'. This probably means you don't have Xcode installed, you will need to launch the app manually and logging output will not be shown!
```

```
/Applications/Xcode.app/Contents/Developer/platforms/iPhoneOS.platform/DeviceSupport$ ls -la
total 0
drwxrwxr-x  17 root  wheel  544 30 Oct 16:30 .
drwxr-xr-x  10 root  wheel  320 10 Oct 15:23 ..
drwxrwxr-x   4 root  wheel  128 28 Jul 16:14 10.0
drwxrwxr-x   4 root  wheel  128 28 Jul 16:15 10.1
drwxrwxr-x   4 root  wheel  128 28 Jul 16:12 10.2
drwxrwxr-x   4 root  wheel  128 28 Jul 16:13 10.3
drwxrwxr-x   5 root  wheel  160 30 Oct 16:13 11.0 (15A372)
lrwxr-xr-x   1 root  wheel   13 30 Oct 16:30 11.0.3 (15A432) -> 11.0 (15A372)
drwxrwxr-x   4 root  wheel  128 28 Jul 16:12 8.0
drwxrwxr-x   4 root  wheel  128 28 Jul 16:12 8.1
drwxrwxr-x   4 root  wheel  128 10 Oct 15:55 8.2
drwxrwxr-x   4 root  wheel  128 28 Jul 16:13 8.3
drwxrwxr-x   4 root  wheel  128 28 Jul 16:14 8.4
drwxrwxr-x   4 root  wheel  128 28 Jul 16:12 9.0
drwxrwxr-x   4 root  wheel  128 28 Jul 16:12 9.1
drwxrwxr-x   4 root  wheel  128 28 Jul 16:13 9.2
drwxrwxr-x   4 root  wheel  128 28 Jul 16:14 9.3
```

**Comment by shazron** [comment] 2017-11-01 03:37
I tried this using iOS 11.1 and Xcode 9.1, it deployed fine. However I had to wait for the debugger symbols to transfer first. Check in `Xcode -> WIndow -> Device and Simulators` for your device. Wait for it to fully copy over.

**Comment by gparsloe** [comment] 2017-11-13 15:15
I had the same problem and got it working just by updating ios-deploy from 1.9.0 to 1.9.2 ($sudo npm install -g ios-deploy@latest).

Problem: running  $ionic cordova run ios --device  resulted in the problem reported by Robertbaelde above.

Setup which had the problem:
macOS 10.12.6 
ios-deploy 1.9.0 
Xcode 8.3.3
Swift-3.1
npm 5.3.0
ionic 3.12.0
cordova 7.0.1
node v6.9.4

Setup which worked (same as above except for ios-deploy): 
ios-deploy 1.9.2
