### ISSUE TITLE
ios-deploy can't deploy to path with special characters

### ISSUE THREAD

**Issue by Charriu** [phonegap/ios-deploy#100] opened 2015-02-09 11:02 UTC
If there are special characters like ("§ ¶¢İı")in the path to the .app, ios-deploy throws an Assertion failed: 
```
(AMDeviceSecureTransferPath(0, device, url, options, transfer_callback, 0)==0), function handle_device, file ios-deploy.c, line 1532.
Abort trap: 6 
```

**Comment by shazron** [comment] 2015-03-03 00:10
Dupe of #56

**Closed by shazron** 2015-03-03 00:10 UTC
Labels: bug
