### ISSUE TITLE
unable to run on device when using UTF8 characters in application name.

### ISSUE THREAD

**Issue by ayaka209** [phonegap/ios-deploy#151] opened 2015-06-14 23:20 UTC
The program can run well using xcode, I also tried another device and got same error.
```
[  0%] Found iPad 4 'iPad' (8b4885373e1c5d9c17fd1bf73d81622717133fb2) connected through USB, beginning install
2015-06-15 07:06:28.137 ios-deploy[38314:7750581] [ !! ] Error 0xe8000008: ∑i~ˇ AMDeviceSecureTransferPath(0, device, url, options, transfer_callback, 0)
Error code 253 for command: ios-deploy with args: -d,-b,/Volumes/W/ProgramDev/elancework/intro_3000/app/platforms/ios/build/device/正念.app
```

cordova version 5.1.1/4.3.0
ios-deploy 1.5.0/1.7.0
```
sw_vers -productVersion
10.10.3
```
```
xcodebuild -version
Xcode 6.3.2
Build version 6D2105
```

```
 xcode-select --print-path
/Applications/Xcode.app/Contents/Developer
```

```
gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/c++/4.2.1
2015-06-15 07:10:59.558 xcodebuild[38326:7753747] [MT] PluginLoading: Required plug-in compatibility UUID E969541F-E6F9-4D25-8158-72DC3545A6C6 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Unity4XC.xcplugin' not present in DVTPlugInCompatibilityUUIDs
Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)
Target: x86_64-apple-darwin14.3.0
Thread model: posix
```
```
lldb --version
lldb-330.0.48
```

**Comment by shazron** [comment] 2015-06-15 17:41
Dupe of #56

**Closed by shazron** 2015-06-15 17:41 UTC
