### ISSUE TITLE
Failure to build with Xcode 9 / macOS 10.13

### ISSUE THREAD

**Issue by fxcoudert** [phonegap/ios-deploy#311] opened 2017-08-24 17:52 UTC
ios-deploy 1.9.1 fails to build on macOS 10.13 (beta 7) with Xcode 9 (beta 6). It's trying to link the `MobileDevice` framework and fails. Full logs are available at https://gist.github.com/28d82c92726c12f3ea1e00a1272a3254 and you can see the error at https://gist.githubusercontent.com/anonymous/28d82c92726c12f3ea1e00a1272a3254/raw/93b0c71e620b453bb9cfd91a1f3f1ebe40f19c62/01.xcodebuild

```
Ld build/Release/ios-deploy normal x86_64
    cd /tmp/ios-deploy-20170824-43592-13gypya/ios-deploy-1.9.1
    export MACOSX_DEPLOYMENT_TARGET=10.8
    /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch x86_64 -isysroot /Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -L/tmp/ios-deploy-20170824-43592-13gypya/ios-deploy-1.9.1/build/Release -F/tmp/ios-deploy-20170824-43592-13gypya/ios-deploy-1.9.1/build/Release -filelist /tmp/ios-deploy-20170824-43592-13gypya/ios-deploy-1.9.1/build/ios-deploy.build/Release/ios-deploy.build/Objects-normal/x86_64/ios-deploy.LinkFileList -mmacosx-version-min=10.8 -Xlinker -object_path_lto -Xlinker /tmp/ios-deploy-20170824-43592-13gypya/ios-deploy-1.9.1/build/ios-deploy.build/Release/ios-deploy.build/Objects-normal/x86_64/ios-deploy_lto.o -fobjc-arc -fobjc-link-runtime -framework MobileDevice -F/System/Library/PrivateFrameworks -framework Foundation -framework CoreFoundation -Xlinker -dependency_info -Xlinker /tmp/ios-deploy-20170824-43592-13gypya/ios-deploy-1.9.1/build/ios-deploy.build/Release/ios-deploy.build/Objects-normal/x86_64/ios-deploy_dependency_info.dat -o /tmp/ios-deploy-20170824-43592-13gypya/ios-deploy-1.9.1/build/Release/ios-deploy
ld: framework not found MobileDevice
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** BUILD FAILED **


The following build commands failed:
	Ld build/Release/ios-deploy normal x86_64
(1 failure)
```

**Comment by shazron** [comment] 2017-08-24 23:13
Duplicate of #308

**Closed by shazron** 2017-08-24 23:13 UTC
