### ISSUE TITLE
Cant access folders in IOS10

### ISSUE THREAD

**Issue by HRMKN** [phonegap/ios-deploy#257] opened 2016-09-23 14:19 UTC
Hi, we are using iso-deploy to access documents folder of an app, with ios 9.3.5 we can do so but with IOS10 we can't anymore..

Any ideas?

For example folders are indeed visible using amazing...

- [10.12 ] 1. sw_vers -productVersion
- [2.0.0 ] 2. ios-deploy -V
- [ ] 3. xcodebuild -version
- [ /Library/Developer/CommandLineTools] 4. xcode-select --print-path
- [ ] 5. gcc --version
- [ ] 6. lldb --version

**Comment by hexenesi** [comment] 2016-09-23 15:31
@HRMKN 
This bug is the same as #241

**Comment by HRMKN** [comment] 2016-09-23 15:46
Ja, ese soy yo!!

**Comment by shazron** [comment] 2016-09-30 00:24
Closing as dupe of #241

**Closed by shazron** 2016-09-30 00:24 UTC
