### ISSUE TITLE
Have to manually pkill ios-deploy.

### ISSUE THREAD

**Issue by 5amfung** [phonegap/ios-deploy#163] opened 2015-08-08 03:54 UTC
The `ios-deploy` processes seem to live on and cause weird issue.  I have to `pkill ios-deploy` every once a while to clean up.  Am I missing something or is it a bug?

**Comment by shazron** [comment] 2015-08-15 02:34
It depends, what arguments are you using to launch it? It has to launch lldb through a python script, so it doesn't have full control (although it tries to catch the relevant signals).

**Comment by 5amfung** [comment] 2015-08-19 06:05
I use `ionic run ios --device` to launch the app.

**Comment by shazron** [comment] 2015-08-20 09:15
Might be an ionic thing (I don't know, and don't have time to debug). Try using the raw iso-deploy and report back.

**Comment by snappa** [comment] 2015-09-16 15:21
@shazron  FYI, I've been seeing the same behavior with the command "ionic run ios --device" orphaning ios-deploy processes and lldb being hung / unresponsive.  I usually have to control-C out of it and periodically I will end up killing lots of ios-deploy processes that have been orphaned.

Running ios-deploy directly and specifying the app bundle on a command line works properly, lets lldb run and when I quit out of lldb it shuts down cleanly.

**Comment by ptarjan** [comment] 2015-09-21 23:38
This is almost certainly https://github.com/phonegap/ios-deploy/issues/169

**Comment by suculent** [comment] 2016-09-23 13:27
Actually ios-deploy does not terminate to me as a standalone (without using ionic).

**Comment by shazron** [comment] 2016-10-21 00:28
Closing as duplicate of #169 where there is a workaround

**Closed by shazron** 2016-10-21 00:28 UTC
Labels: follow-up
